permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 紫气东来
  email: tsthght@163.com
  link: 
  weibo: 
  github: http://github.com/tsthght

# 站点信息
title: Tsthght的博客
description: My personal blog
rss_url: /pages/atom.xml

# disqus 设置
disqus:
  shortname: tsthght

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
